### ISSUE TITLE
`A.torch_matvec()` changes the shape of tensors

### ISSUE THREAD

**Issue by BrunoKM** [f-dangel/curvlinops#124]
When `A` is a `KFACLinearOperator` or `KFACInverseLinearOperator` for model parameters given by a list of tensors, the expected behaviour when applying `A` to a list of tensors of the same shape would be that it returns a list of the same shape. This is not the case:
```python
params = [torch.zeros(5,4), torch.zeros(5, 3, 3, 3)]
A = KFACLinearOperator(
    ...
    params,
    ...
)
v = [torch.randn_like(p) for p in params]
y = A.torch_matvec(v)
print([y_elem.shape for y in y_elem])
# Expected output: same shapes as `v` and `params`:
>>> [(5, 4), (5, 3, 3, 3)]
# Actual output: flattened to a 2D tensor:
>>> [(5, 4), (5, 27)]
```

**Comment by f-dangel** [comment]
Hi,

that's indead weird. `KFACLinearOperator` expects `params` to be used by whatever you supply as `model_func` argument. What neural network are you using? Anyways this seems like the checks on `params` are not sufficient to catch this.

**Comment by BrunoKM** [comment]
Yup, exactly! This was just an illustrative example, I noticed this in a larger resnet where every parameter ended up being flattened to at most 2D.

**Comment by f-dangel** [comment]
Could you set up a PR to fix this? I guess you already have a small example to reproduce this, which we could use as test in the future.

**Comment by BrunoKM** [comment]
Yeah, I could have a look. I'll tag @runame because he might have already looked into this.

**Comment by runame** [comment]
Sorry about the delay, I know where the bug is, just haven't fixed it yet. Will create a PR later today.
