### ISSUE TITLE
`KFACLinearOperator` deterministic checks break when using double precision

### ISSUE THREAD

**Issue by liaodisen** [f-dangel/curvlinops#132]
I want to use my model in double precision, so I need to pass in data in double precision, but I will have error, here is I reproduced the error with toy example by changing precision:
```Python
# make deterministic
torch.manual_seed(0)
numpy.random.seed(0)

N = 4
D_in = 7
D_hidden = 5
D_out = 3
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

X = torch.rand(N, D_in, dtype=torch.float64).to(DEVICE)
y = torch.rand(N, D_out, dtype=torch.float64).to(DEVICE)

model = nn.Sequential(
    nn.Linear(D_in, D_hidden),
    nn.ReLU(),
    nn.Linear(D_hidden, D_hidden),
    nn.Sigmoid(),
    nn.Linear(D_hidden, D_out),
).double().to(DEVICE)
params = [p for p in model.parameters() if p.requires_grad]
data = [(X, y)]
loss_function = nn.MSELoss(reduction="mean").to(DEVICE)
KH = KFACLinearOperator(model, loss_function, params, data)
```

And the error I got is:

> Traceback (most recent call last):
>   File "/home/d7liao/TGDA-Attack/example.py", line 34, in <module>
>     KH = KFACLinearOperator(model, loss_function, params, data)
>   File "/home/d7liao/anaconda3/envs/traits/lib/python3.10/site-packages/curvlinops/kfac.py", line 284, in __init__
>     raise e
>   File "/home/d7liao/anaconda3/envs/traits/lib/python3.10/site-packages/curvlinops/kfac.py", line 282, in __init__
>     self._check_deterministic()
>   File "/home/d7liao/anaconda3/envs/traits/lib/python3.10/site-packages/curvlinops/_base.py", line 195, in _check_deterministic
>     mat_v1 = self @ v
>   File "/home/d7liao/anaconda3/envs/traits/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py", line 455, in __matmul__
>     return self.__mul__(other)
>   File "/home/d7liao/anaconda3/envs/traits/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py", line 411, in __mul__
>     return self.dot(x)
>   File "/home/d7liao/anaconda3/envs/traits/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py", line 444, in dot
>     return self.matvec(x)
>   File "/home/d7liao/anaconda3/envs/traits/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py", line 236, in matvec
>     y = self._matvec(x)
>   File "/home/d7liao/anaconda3/envs/traits/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py", line 203, in _matvec
>     return self.matmat(x.reshape(-1, 1))
>   File "/home/d7liao/anaconda3/envs/traits/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py", line 340, in matmat
>     Y = self._matmat(X)
>   File "/home/d7liao/anaconda3/envs/traits/lib/python3.10/site-packages/curvlinops/kfac.py", line 527, in _matmat
>     M_torch = self.torch_matmat(M_torch)
>   File "/home/d7liao/anaconda3/envs/traits/lib/python3.10/site-packages/curvlinops/kfac.py", line 463, in torch_matmat   
>     M_torch[pos] = einsum(
>   File "/home/d7liao/anaconda3/envs/traits/lib/python3.10/site-packages/einops/einops.py", line 907, in einsum
>     return get_backend(tensors[0]).einsum(pattern, *tensors)
>   File "/home/d7liao/anaconda3/envs/traits/lib/python3.10/site-packages/einops/_backends.py", line 287, in einsum
>     return self.torch.einsum(pattern, *x)
>   File "/home/d7liao/anaconda3/envs/traits/lib/python3.10/site-packages/torch/functional.py", line 378, in einsum
>     return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
> RuntimeError: expected scalar type Float but found Double

> 
Thanks in advance

**Comment by f-dangel** [comment]
Hi Dison,

I just pushed a patch here (#133). Could you install from that branch and check if it resolves your issue? (It does for me locally).

Thanks for reporting this,
Felix
