### ISSUE TITLE
Feature request: Diagonal estimation algorithms

### ISSUE THREAD

**Issue by f-dangel** [f-dangel/curvlinops#31]
Similar to Hutchinson's method for trace estimation, one can approximate the diagonal of a matrix from projections onto random vectors, see for instance [Equation 16](https://arxiv.org/pdf/1206.6464.pdf), or [Equation 9](https://arxiv.org/pdf/2006.00719.pdf).

There are no implementations for Hessian diagonal estimation in `scipy`, so it would be nice to offer such methods through a `LinearOperator` interface through this library.

**Comment by andres-fr** [comment]
Interesting! I was only aware of the "classical" Becker-LeCun method, which I believe has the cost of a second backprop pass (not 100% sure on this): http://yann.lecun.com/exdb/publis/pdf/becker-lecun-89.pdf

Would the Becker-LeCun method be exact? In that case, what would be the advantage of doing Hutchinson, which is approximate and requires multiple HVPs?

**Comment by f-dangel** [comment]
As far as I understand Becker-LeCun, it is not exact unless you make very strong assumptions (e.g. you have an MLP with diagonal weight matrices). So while it might sometimes get close to the Hessian diagonal, I don't know any hard results like an error of the approximation bound, or whether it is unbiased (my intuition would be that it is biased and the error can be arbitrary in general).
