### ISSUE TITLE
Feature request: add method to convert to matrix

### ISSUE THREAD

**Issue by andres-fr** [f-dangel/curvlinops#41]
To convert a linear operator to an explicit matrix, we need the following one-liner:

```
matrix = operator @ np.eye(operator.shape[-1])
```
SciPy also has the [aslinearoperator](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.aslinearoperator.html#scipy.sparse.linalg.aslinearoperator) function, that converts a matrix to an operator.

What do you think about adding a method that does the converse, i.e.

```
matrix = operator.asmatrix()
```

It would basically involve the one-liner above. Pros, cons?

**Comment by andres-fr** [comment]
One pro I can think of, is that an iterative implementation would save the need for creating a (potentially large) identity matrix.
Another advantage is that abstracting this may allow to introduce arguments, e.g. for sampled approximations.

Possible disadvantage: inconsistency with SciPy interface

**Comment by f-dangel** [comment]
Yeah, this could be a reasonable idea to implement if we figure out what useful arguments are. One thing that comes to my mind would be to compute only sub-matrices. For instance
```python
def asmatrix(self, row_idxs = None, col_idxs = None): -> ndarray:
   """Compute an explicit matrix representation.

    row_idxs: Sub-set of rows.
    col_idxs: Sub-set of columns.
  """
  ...
```

I also think it may be possible to improve performance for some linear operators, e.g. `Jacobian`, `TransposeJacobian`.

**Comment by andres-fr** [comment]
Absolutely, I'd go with that! Idxs should be allowed to be a generator imo

**Comment by f-dangel** [comment]
At the moment I have no strong reasons to add this. Please re-open if there is strong benefit of having specialized implementations of converting a linear operator into a matrix. Otherwise, use the suggested way of
```python
matrix = operator @ np.eye(operator.shape[-1])
```
to convert a linear operator into its matrix representation.
