### ISSUE TITLE
Support type-2 Fisher in KFAC

### ISSUE THREAD

**Issue by runame** [f-dangel/curvlinops#49]
As opposed to using MC samples from the model's predictive distribution.

**Comment by f-dangel** [comment]
Question: Is this already implemented in [`curvlinops.GGNLinearOperator`](https://curvlinops.readthedocs.io/en/latest/linops.html#generalized-gauss-newton)?

**Comment by runame** [comment]
I don't think so, because [curvlinops.GGNLinearOperator](https://curvlinops.readthedocs.io/en/latest/linops.html#generalized-gauss-newton) computes the exact GGN/Fisher, whereas this issue request a KFAC approximation using one backward pass per output dimension (see the [implementation in ASDL](https://github.com/kazukiosawa/asdl/blob/master/asdl/fisher.py#L418-L439) as an example) to compute the gradients. I realize that the naming of the issue is a bit confusing, since it says "exact Fisher/GGN".

**Comment by f-dangel** [comment]
Oh okay, so this is sampling gradients versus using the columns of the loss-output Hessian's matrix square root? (I think in BackPACK this corresponds to KFLR)

**Comment by runame** [comment]
Yeah, that sounds correct.
